"""Python port of the MATLAB `TPJBSolver` class (isothermal configuration).

The goal of this module is to stay close to the original MATLAB code while
providing a Pythonic interface built on top of NumPy.  The implementation is a
line-by-line translation where possible; vectorised constructs such as
`pagemtimes` are emulated with helper utilities.

This file was generated by porting `TPJBSolver.m` to Python.
"""

from __future__ import annotations

from dataclasses import dataclass
from types import SimpleNamespace
from typing import Any, Dict, Iterable, Tuple

import numpy as np


Array = np.ndarray


def _ns(defaults: Dict[str, Any] | None = None, **overrides: Any) -> SimpleNamespace:
    data: Dict[str, Any] = {}
    if defaults:
        data.update(defaults)
    data.update(overrides)
    return SimpleNamespace(**data)


def _col(vec: Iterable[float]) -> Array:
    arr = np.asarray(list(vec), dtype=float)
    if arr.ndim == 1:
        return arr.reshape(-1, 1)
    return arr


def _to_rad(angle_deg: Array) -> Array:
    return np.deg2rad(angle_deg)


@dataclass
class SolverOutcome:
    zeq: Array
    K: Array
    C: Array
    sommerfeld: float
    load: float
    lambda_min: float


class TPJBSolver:
    """Direct Python translation of the MATLAB TPJBSolver class."""

    def __init__(
        self,
        geom: Dict[str, Any],
        op: Dict[str, Any] | None = None,
        asp: Dict[str, Any] | None = None,
        opt: Dict[str, Any] | None = None,
    ) -> None:
        op = {} if op is None else dict(op)
        asp = {} if asp is None else dict(asp)
        opt = {} if opt is None else dict(opt)

        opt.setdefault("Nx", 30)
        opt.setdefault("Nz", 17)
        opt.setdefault("Ny", 9)
        opt.setdefault("Dyn", 0)
        opt.setdefault("Cav", 1)
        opt.setdefault("Half", 0)
        opt.setdefault("surfPlot", 0)

        ref_state = _ns()
        ref_state.rfP = 1.0
        ref_state.pAmb = 1e5
        ref_state.pRef = 1e6
        ref_state.pCav = 3e4
        ref_state.nx = int(opt["Nx"])
        ref_state.nz = int(opt["Nz"])
        ref_state.ny = int(opt["Ny"])
        ref_state.nyPad = 5
        ref_state.nySft = 5
        ref_state.vsn = np.finfo(float).eps
        ref_state.errJFO = 1e-6
        ref_state.thetaF = 0.0
        ref_state.omega = 1000 * np.pi / 30

        if "pAmb" in op:
            ref_state.pAmb = float(op["pAmb"])
        if "pCav" in op:
            ref_state.pCav = float(op["pCav"])
        if "pRef" in op:
            ref_state.pRef = float(op["pRef"])
        if "omega" in op:
            ref_state.omega = float(op["omega"])

        options = _ns()
        options.Dyn = bool(opt["Dyn"])
        options.Piv = False
        options.Paddfm = False
        options.Dim3 = False
        options.Trans = False
        options.Half = bool(opt["Half"])
        options.GwFit = True
        options.Cav = bool(opt["Cav"])
        options.dispErrJFO = False
        options.surfPlot = bool(opt["surfPlot"])
        options.Thermal = 0

        bearing_diameter = float(geom["D"])
        bearing_length = float(geom["L"])
        bearing_clearance = float(geom["clearance"])
        length_to_diameter = bearing_length / bearing_diameter
        # clearance_ratio = bearing_clearance / bearing_diameter  # kept for parity with MATLAB, currently unused
        pad_count = int(geom["n_pad"])
        pad_arc_angle = float(geom["pad_angle"])
        preload = float(geom["preload"])
        groove_angle = float(geom["groove_angle"])
        reference_pad_angle = float(geom["ref_pad_angle"])

        bearing = _ns()
        bearing.Tilt = 0.0
        bearing.Mp = preload
        bearing.LD = length_to_diameter
        bearing.pad_count = pad_count
        bearing.aPad = pad_arc_angle
        bearing.aGrv = groove_angle
        bearing.refPadTa = reference_pad_angle
        bearing.padOff = 0.5 * np.ones(pad_count)
        bearing.padThc = 50e-3 * np.ones(pad_count)
        bearing.padRot = np.zeros(pad_count)
        bearing.Db = bearing_diameter
        bearing.Lb = bearing_length
        bearing.Cb = bearing_clearance
        bearing.Cp = bearing_clearance / (1 - preload)
        bearing.KPv = 1e12
        bearing.pIn = ref_state.pAmb
        bearing.pOut = ref_state.pAmb
        bearing.pM = ref_state.pAmb
        bearing.pP = ref_state.pAmb
        bearing.PDBC = np.array([1, 1, 1, 1], dtype=int)
        bearing.Rb = bearing_diameter / 2
        bearing.w = 0.0
        bearing.u = bearing.Rb * ref_state.omega

        total_dofs = 2 * (2 + 2 * pad_count)
        basis = np.eye(total_dofs)

        def fdZ(idx: int) -> Array:
            # MATLAB indexing starts at 1; adjust accordingly.
            return basis[:, idx - 1]

        bearing.fdZ = fdZ

        lubricant = _ns({
            "mu0": 0.0138,
            "beta": 0.0,
            "T0": 40.0,
            "rhoL": 860.0,
            "cpL": 2000.0,
            "kL": 0.13,
            "TSup": 30.0,
        })
        if "mu0" in op:
            lubricant.mu0 = float(op["mu0"])

        thermal = _ns({
            "TIni": 40.0,
            "TIn": 40.0,
            "TShaft": 40.0,
            "TPad": 40.0,
            "TDBC": np.array([1, 1, 1]),
            "TInf": 18.0,
            "hConv": 80.0,
            "kS": 1.0,
            "kP": 1.0,
        })

        shN, shB, shW, shdW, shQ, weights, GP, nGI = self.sub_shape_funs(4)
        ref_state.GP = GP
        ref_state.nGI = nGI
        ref_state.shN = shN
        ref_state.shB = shB
        ref_state.shW = shW
        ref_state.shdW = shdW
        ref_state.shQ = shQ
        ref_state.weights = weights

        pad_total = pad_count
        grid_points_x = ref_state.nx
        grid_points_z = ref_state.nz
        grid_points_y = ref_state.ny
        is_half_domain = options.Half
        bearing_radius = bearing.Rb

        pad_angle = (
            np.full((pad_total, 2), bearing.refPadTa)
            + (bearing.aGrv + bearing.aPad) * np.arange(pad_total)[:, None]
            + np.array([-pad_arc_angle / 2, pad_arc_angle / 2])[None, :]
        )
        theta_pad = _to_rad(pad_angle)
        theta_ta = theta_pad[:, 0] + bearing.padOff * (theta_pad[:, 1] - theta_pad[:, 0])
        bearing.thetaPad = theta_pad

        nx_fine = int(np.ceil(bearing.aPad / 0.25) + 1)
        mat_th = np.zeros(grid_points_x * pad_total)
        vec_r = np.zeros((grid_points_x - 1) * pad_total)
        vec_th = np.zeros((grid_points_x - 1) * pad_total)
        mat_th_fine = np.zeros(nx_fine * pad_total)
        vec_r_fine = np.zeros((nx_fine - 1) * pad_total)
        vec_th_fine = np.zeros((nx_fine - 1) * pad_total)

        for i in range(pad_total):
            th = np.linspace(theta_pad[i, 0], theta_pad[i, 1], grid_points_x)
            mat_th[i * grid_points_x : (i + 1) * grid_points_x] = th
            avg_th = 0.5 * (th[:-1] + th[1:])
            Rp = bearing_radius + bearing.Cp + bearing.padThc[i]
            loc_pv = Rp * np.array([np.cos(theta_ta[i]), np.sin(theta_ta[i])])
            loc_node = (bearing_radius + bearing.Cp) * np.vstack((np.cos(avg_th), np.sin(avg_th)))
            pv_to_node = np.vstack((loc_node - loc_pv[:, None], np.zeros(avg_th.shape)))
            o_to_node = np.vstack((np.cos(avg_th), np.sin(avg_th), np.zeros(avg_th.shape)))
            r_vec = np.cross(pv_to_node.T, o_to_node.T).T
            vec_r[i * (grid_points_x - 1) : (i + 1) * (grid_points_x - 1)] = r_vec[2]
            vec_th[i * (grid_points_x - 1) : (i + 1) * (grid_points_x - 1)] = avg_th

            thf = np.linspace(theta_pad[i, 0], theta_pad[i, 1], nx_fine)
            mat_th_fine[i * nx_fine : (i + 1) * nx_fine] = thf
            avg_th_f = 0.5 * (thf[:-1] + thf[1:])
            loc_node_f = (bearing_radius + bearing.Cp) * np.vstack((np.cos(avg_th_f), np.sin(avg_th_f)))
            pv_to_node_f = np.vstack((loc_node_f - loc_pv[:, None], np.zeros(avg_th_f.shape)))
            o_to_node_f = np.vstack((np.cos(avg_th_f), np.sin(avg_th_f), np.zeros(avg_th_f.shape)))
            r_vec_f = np.cross(pv_to_node_f.T, o_to_node_f.T).T
            vec_r_fine[i * (nx_fine - 1) : (i + 1) * (nx_fine - 1)] = r_vec_f[2]
            vec_th_fine[i * (nx_fine - 1) : (i + 1) * (nx_fine - 1)] = avg_th_f

        pressure_state = _ns()
        pressure_state.thetaTa = theta_ta
        pressure_state.matTh = np.tile(mat_th, (grid_points_z, 1))
        pressure_state.vecR = vec_r.reshape(pad_total, -1)
        pressure_state.vecTh = vec_th.reshape(pad_total, -1)
        pressure_state.matTh_fine = np.tile(mat_th_fine, (grid_points_z, 1))
        pressure_state.vecR_fine = vec_r_fine.reshape(pad_total, -1)
        pressure_state.vecTh_fine = vec_th_fine.reshape(pad_total, -1)
        z_line = np.linspace(-bearing_length / 2 * (not is_half_domain), bearing_length / 2, grid_points_z)
        pressure_state.matZ = z_line[:, None] * np.ones((1, grid_points_x * pad_total))
        matZ_fine = z_line[:, None] * np.ones((1, nx_fine * pad_total))
        pressure_state.matZ_fine = matZ_fine.reshape(grid_points_z, nx_fine, pad_total)

        matP = np.zeros((grid_points_z, grid_points_x * pad_total))
        if bearing.PDBC[0] == 1:
            matP[:, ::grid_points_x] = 1
        if bearing.PDBC[1] == 1:
            matP[:, grid_points_x - 1 :: grid_points_x] = 2
        if bearing.PDBC[2] == 1:
            matP[0, :] = 3
        if bearing.PDBC[3] == 1 and not is_half_domain:
            matP[-1, :] = 4
        matP1 = matP[:, :grid_points_x]
        nodeNp = matP1.ravel(order="F") == 0
        for code, value in zip([1, 2, 3, 4], [bearing.pIn, bearing.pOut, bearing.pM, bearing.pP]):
            matP[matP == code] = value
        matP[matP == 0] = ref_state.pAmb
        iN = nodeNp != 0
        iP = np.flatnonzero(~iN)
        nNode = grid_points_x * grid_points_z
        iP = (iP[:, None] * nNode + iP).ravel()

        if options.Cav:
            matC = ref_state.vsn * np.ones((grid_points_z, grid_points_x * pad_total))
            if bearing.pIn > ref_state.pCav:
                matC[:, ::grid_points_x] = 0
        else:
            matC = np.zeros((grid_points_z, grid_points_x * pad_total))

        matNCP, _, _, matNNP = self.sub_2d_mesh(grid_points_z, grid_points_x)
        pressure_state.NCP = matNCP
        pressure_state.NNP = matNNP
        pad_offsets = np.arange(pad_total) * grid_points_x * grid_points_z
        pressure_state.pNP = np.tile(matNNP.ravel(order="F")[:, None], (1, pad_total)) + pad_offsets
        pressure_state.pNP = pressure_state.pNP.astype(int)
        pressure_state.iNP = iN
        pressure_state.BCP = matP[:, :grid_points_x].ravel(order="F")[~iN]
        pressure_state.iPDP = iP
        pressure_state.iNC = np.array([], dtype=int)
        pressure_state.BCC = np.array([], dtype=float)
        e2R = np.tile(np.arange(grid_points_z)[:, None], (1, grid_points_x))
        e2C = np.tile(np.arange(grid_points_x)[None, :], (grid_points_z, 1))
        pressure_state.NC2cP = e2C[matNCP]
        matNN2 = matNNP[iN]
        pressure_state.NNPNP = matNN2
        pressure_state.NNPNC = np.array([], dtype=int)

        matNCT, _, _, matNNT = self.sub_2d_mesh(grid_points_y, grid_points_x)
        temperature_state = _ns()
        temperature_state.NCT = matNCT
        temperature_state.NNT = matNNT
        temperature_state.pNT = np.tile(matNNT.ravel(order="F")[:, None], (1, pad_total)) + np.arange(pad_total) * grid_points_x * opt["Ny"]
        temperature_state.pNT = temperature_state.pNT.astype(int)
        temperature_state.matT = thermal.TIni * np.ones((opt["Ny"], grid_points_x * pad_total))
        temperature_state.matThT = np.tile(mat_th, (opt["Ny"], 1))

        self.z_equilibrium = np.zeros(total_dofs)
        self.stiffness_matrix = np.zeros((2, 2))
        self.damping_matrix = np.zeros((2, 2))
        self.last_error = np.nan
        self.last_iteration = 0
        self.sommerfeld_number = np.nan

        asperity = _ns()
        asperity.sig = 1e-6
        asperity.cof_fric = 0.1
        asperity.den = 2.2e10
        asperity.radius = 1.5e-6

        for key in ("sig", "cof_fric", "den", "radius"):
            if key in asp:
                setattr(asperity, key, float(asp[key]))

        asperity.f_fp = lambda H: (1 - 0.9 * np.exp(-H)) * (H >= 0.5)
        asperity.f_fs = lambda H: (
            (1.899 * H ** 0.98 * np.minimum(np.exp(-0.92 * H + 0.05 * H ** 2), np.exp(10))) * (H <= 5)
            + (1.126 * np.exp(-0.25 * H)) * (H > 5)
        )
        asperity.f_ff_p = lambda H: (1 - 1.4 * np.exp(-0.66 * H)) * (H >= 0.5)
        asperity.f_ff_s = lambda H: (
            11.1 * H ** 2.31 * np.exp(-2.38 * H + 0.11 * H ** 2) * (H >= 0.5)
        )
        asperity.f_ht = lambda z, sig: (
            (3 * sig / 256) * (35 + z * (128 + z * (140 + z ** 2 * (-70 + z ** 2 * (28 - 5 * z ** 2))))) * (z < 1)
            + 3 * sig * z * (z >= 1)
        )
        asperity.f_ff = lambda z: (
            35 / 32
            * z
            * (
                ((1 - z ** 2) ** 3 * np.log((z + 1) * 300) + (1 / 60) * (-55 + z * (132 + z * (345 + z * (-160 + z * (-405 + z * (60 + 147 * z))))))) * (z <= 1)
                + ((1 - z ** 2) ** 3 * np.log((z + 1) / (z - 1)) + z / 15 * (66 + z ** 2 * (30 * z ** 2 - 80))) * (z > 1)
            )
        )

        E_c = 2.07e11
        fac_gt = 8 * np.sqrt(2) / 15 * np.pi * (asperity.den * asperity.radius * asperity.sig) ** 2 * np.sqrt(asperity.sig / asperity.radius)
        asperity.f_p_cont = lambda H: fac_gt * E_c * (4.4086e-5 * np.maximum(4 - H, 0) ** 6.08) * (H < 4)

        initial_state = np.zeros(total_dofs)
        initial_state[:2] = bearing_clearance * 0.1 * np.array([np.cos(0), np.sin(0)])

        self.state_vector = initial_state
        self.pressure_state = pressure_state
        self.temperature_state = temperature_state
        self.bearing = bearing
        self.ref_state = ref_state
        self.options = options
        self.lubricant = lubricant
        self.thermal = thermal
        self.asperity = asperity
        self.nx = grid_points_x
        self.nz = grid_points_z
        self.ny = grid_points_y
        self.pad_count = pad_total
        self.nx_fine = nx_fine

        matP_all = (matP - ref_state.pCav) / (ref_state.pRef - ref_state.pCav)
        idx_pad = pressure_state.pNP.astype(int)
        self.matTh_flat = pressure_state.matTh.ravel(order="F")[idx_pad]
        self.matZ_flat = pressure_state.matZ.ravel(order="F")[idx_pad]
        self.matP_flat = matP_all.ravel(order="F")[idx_pad]
        self.matC_flat = matC.ravel(order="F")[idx_pad]
        self.matT_flat = temperature_state.matT.ravel(order="F")[temperature_state.pNT.astype(int)]

        self.vecR = pressure_state.vecR
        self.vecThAvg = pressure_state.vecTh
        self.vecThLine = mat_th.reshape(pad_total, grid_points_x)
        self.matTh_fine = pressure_state.matTh_fine.reshape(grid_points_z, nx_fine, pad_total)
        self.matZ_fine = pressure_state.matZ_fine
        self.vecR_fine = pressure_state.vecR_fine
        self.vecThAvg_fine = pressure_state.vecTh_fine
        self.vecThLine_fine = mat_th_fine.reshape(pad_total, nx_fine)
        self.p_lub = np.zeros((grid_points_z, grid_points_x, pad_total))
        self.p_cont = np.zeros((grid_points_z, nx_fine, pad_total))
        self.matP_all = matP_all
        self.force_lubrication = np.zeros(2)
        self.force_contact = np.zeros(2)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def set_operating(self, acond: Dict[str, Any]) -> SolverOutcome:
        acond = dict(acond)
        bearing_diameter = self.bearing.Db
        bearing_length = self.bearing.Lb
        pad_clearance = self.bearing.Cp
        lubricant_viscosity = self.lubricant.mu0

        sommerfeld_target = acond.get("S")
        load = acond.get("load")
        shaft_speed = acond.get("omega")

        if sommerfeld_target is not None and load is not None:
            sommerfeld_target = float(sommerfeld_target)
            load = float(load)
            omega_iter = load * sommerfeld_target / (
                lubricant_viscosity
                * bearing_diameter
                * bearing_length
                * (bearing_diameter / 2 / pad_clearance) ** 2
            ) * (2 * np.pi)
            iteration_values = np.atleast_1d(omega_iter)
            mode = "load"
        elif sommerfeld_target is not None and shaft_speed is not None:
            sommerfeld_target = float(sommerfeld_target)
            shaft_speed = float(shaft_speed)
            load_iter = (
                lubricant_viscosity
                * shaft_speed
                / (2 * np.pi)
                * bearing_diameter
                * bearing_length
                * (bearing_diameter / 2 / pad_clearance) ** 2
                / sommerfeld_target
            )
            iteration_values = np.atleast_1d(load_iter)
            mode = "speed"
        else:
            raise ValueError("`set_operating` requires either (S & load) or (S & omega).")

        iteration_count = iteration_values.size
        equilibrium_history = np.zeros((iteration_count, self.state_vector.size))
        stiffness_history = np.zeros((iteration_count, 4))
        damping_history = np.zeros((iteration_count, 4))
        lambda_history = np.zeros(iteration_count)
        load_history = np.zeros(iteration_count)

        for idx in range(iteration_count):
            if mode == "load":
                omg = float(iteration_values[idx])
                load_val = load
            else:
                omg = shaft_speed
                load_val = float(iteration_values[idx])

            self.bearing.u = bearing_diameter / 2 * omg
            self.bearing.ep_jp = min(self.bearing.Cp / 1e3, self.asperity.sig)
            self.bearing.ep_jv = self.bearing.ep_jp * omg / 1e2
            self.bearing.ep_pt = 1e-6
            self.bearing.ep_pa = self.bearing.ep_pt * omg
            self.bearing.ep_pvd = self.bearing.ep_jp
            self.bearing.ep_pvv = self.bearing.ep_jv

            self.ref_state.Fex = load_val * np.array([np.cos(self.ref_state.thetaF), np.sin(self.ref_state.thetaF)])

            # self.bearing.ep_jv = self.bearing.ep_jp * omg / 1e2  # redundant with assignment above

            zeq, matP, K_, C_, lambda_val, out = self.solve_equilibrium(self.state_vector, self)
            equilibrium_history[idx, :] = zeq
            stiffness_history[idx, :] = K_.reshape(-1)
            damping_history[idx, :] = C_.reshape(-1)
            lambda_history[idx] = lambda_val
            load_history[idx] = load_val

            self.state_vector = zeq
            self.z_equilibrium = zeq
            self.stiffness_matrix = K_
            self.damping_matrix = C_
            self.last_error = out["err"]
            self.last_iteration = out["iter"]

        self.sommerfeld_number = sommerfeld_target if sommerfeld_target is not None else np.nan
        return SolverOutcome(
            zeq=equilibrium_history.squeeze(),
            K=stiffness_history.reshape(iteration_count, 2, 2).squeeze(),
            C=damping_history.reshape(iteration_count, 2, 2).squeeze(),
            sommerfeld=self.sommerfeld_number,
            load=float(load_history[-1]),
            lambda_min=float(lambda_history[-1]),
        )

    def force(self, displacement: Iterable[float], velocity: Iterable[float]) -> Tuple[Array, Array]:
        displacement = np.asarray(displacement, dtype=float).reshape(2)
        velocity = np.asarray(velocity, dtype=float).reshape(2)

        trial_state = self.z_equilibrium.copy()
        if trial_state.size == 0:
            trial_state = self.state_vector.copy()
        trial_state[:2] = displacement
        offset = 2 + 2 * self.pad_count
        trial_state[offset : offset + 2] = velocity
        trial_state[offset + 2 : offset + 2 + self.pad_count] = 0.0
        trial_state[offset + 2 + self.pad_count : offset + 2 + 2 * self.pad_count] = 0.0

        pad_force = np.zeros((2, self.pad_count))
        pad_moment = np.zeros(self.pad_count)
        lubrication_force_components = np.zeros((2, self.pad_count))
        contact_force_components = np.zeros((2, self.pad_count))

        for pad_index in range(self.pad_count):
            idx = self.pad_idx(pad_index + 1, self.pad_count)
            res = self.solveP_simplified(
                trial_state[idx - 1],
                self.pressure_state.thetaTa[pad_index],
                self.matTh_flat[:, pad_index],
                self.matZ_flat[:, pad_index],
                self.matP_flat[:, pad_index],
                self.matC_flat[:, pad_index],
                self.matT_flat[:, pad_index],
                self.vecR[pad_index],
                self.vecThAvg[pad_index],
                self.matTh_fine[:, :, pad_index],
                self.vecR_fine[pad_index],
                self.vecThAvg_fine[pad_index],
                self,
            )
            (
                pad_moment[pad_index],
                pad_force[:, pad_index],
                P_,
                p_lub_,
                p_cont_,
                lubrication_force_components[:, pad_index],
                contact_force_components[:, pad_index],
            ) = res
            self.matP_flat[:, pad_index] = P_.ravel(order="F")
            self.p_lub[:, :, pad_index] = p_lub_
            self.p_cont[:, :, pad_index] = p_cont_

        total_force = pad_force.sum(axis=1)
        self.force_lubrication = lubrication_force_components.sum(axis=1)
        self.force_contact = contact_force_components.sum(axis=1)
        return total_force, pad_moment

    # ------------------------------------------------------------------
    # Static helpers
    # ------------------------------------------------------------------

    @staticmethod
    def pad_idx(cP: int, n_pad: int) -> Array:
        base = np.array([1, 2, cP + 2, cP + 2 + n_pad])
        return np.concatenate((base, base + 2 + 2 * n_pad))

    @staticmethod
    def solve_equilibrium(initial_state: Array, obj: "TPJBSolver"):
        state = initial_state.copy()
        pad_total = obj.pad_count
        Rb = obj.bearing.Rb
        Cb = obj.bearing.Cb
        Cp = obj.bearing.Cp
        fdZ = obj.bearing.fdZ
        ep_jp = obj.bearing.ep_jp
        ep_jv = obj.bearing.ep_jv
        sig = obj.asperity.sig
        pad_force = np.zeros((2, pad_total))
        err = 1.0
        tol = 1e-6
        iter_count = 0
        max_iter = 60
        JacF = np.zeros((2, 2))

        while err > tol and iter_count < max_iter:
            for pad_index in range(pad_total):
                idx = TPJBSolver.pad_idx(pad_index + 1, pad_total)
                _pad_moment, pad_force_vec, P_, p_lub_, p_cont_, *_ = TPJBSolver.solveP_simplified(
                    state[idx - 1],
                    obj.pressure_state.thetaTa[pad_index],
                    obj.matTh_flat[:, pad_index],
                    obj.matZ_flat[:, pad_index],
                    obj.matP_flat[:, pad_index],
                    obj.matC_flat[:, pad_index],
                    obj.matT_flat[:, pad_index],
                    obj.vecR[pad_index],
                    obj.vecThAvg[pad_index],
                    obj.matTh_fine[:, :, pad_index],
                    obj.vecR_fine[pad_index],
                    obj.vecThAvg_fine[pad_index],
                    obj,
                )
                pad_force[:, pad_index] = pad_force_vec
                obj.matP_flat[:, pad_index] = P_.ravel(order="F")
                obj.p_lub[:, :, pad_index] = p_lub_
                obj.p_cont[:, :, pad_index] = p_cont_

            F0 = pad_force.sum(axis=1)
            err = np.linalg.norm(F0 + obj.ref_state.Fex) / max(1.0, np.linalg.norm(obj.ref_state.Fex))
            if err <= tol:
                hmin = np.full(pad_total, np.inf)
                for pad_index in range(pad_total):
                    idx = TPJBSolver.pad_idx(pad_index + 1, pad_total)
                    dep = np.zeros(2)
                    h_vals = TPJBSolver.film_thickness_vec(
                        state[idx - 1] + np.concatenate((dep, np.zeros(6))),
                        Rb,
                        Cb,
                        Cp,
                        obj.bearing.Mp,
                        obj.pressure_state.thetaTa[pad_index],
                        obj.vecThLine[pad_index],
                    )
                    hmin[pad_index] = h_vals.min()
                lambda_val = hmin.min() / sig
                matP = obj.matP_flat * (obj.ref_state.pRef - obj.ref_state.pCav) + obj.ref_state.pCav
                out = {"iter": iter_count, "err": err}
                return state, matP, -JacF, np.zeros((2, 2)), lambda_val, out

            Fjpp = np.zeros((2 + 2 * pad_total, 2))
            Fjpm = np.zeros_like(Fjpp)
            for i in range(2):
                Fjpp[:, i] = TPJBSolver.getF(state + ep_jp * fdZ(i + 1), obj)
                Fjpm[:, i] = TPJBSolver.getF(state - ep_jp * fdZ(i + 1), obj)
            JacF = (Fjpp[:2, :2] - Fjpm[:2, :2]) / (2 * ep_jp)
            dep = -np.linalg.solve(JacF, F0 + obj.ref_state.Fex)

            a = 1.0
            for pad_index in range(pad_total):
                good = False
                idx = TPJBSolver.pad_idx(pad_index + 1, pad_total)
                while not good:
                    hmin = TPJBSolver.film_thickness_vec(
                        state[idx - 1] + np.concatenate((a * dep, np.zeros(6))),
                        Rb,
                        Cb,
                        Cp,
                        obj.bearing.Mp,
                        obj.pressure_state.thetaTa[pad_index],
                        obj.vecThLine[pad_index],
                    ).min()
                    if hmin <= 0.5 * sig:
                        a /= 1.5
                        if a < 1e-6:
                            break
                    else:
                        good = True
                if a < 1e-6:
                    break
            state[:2] = state[:2] + a * dep
            iter_count += 1

        matP = obj.matP_flat * (obj.ref_state.pRef - obj.ref_state.pCav) + obj.ref_state.pCav
        C = np.zeros((2, 2))
        if obj.options.Dyn:
            ep_idx = np.arange(2) + (2 + 2 * pad_total)
            Fjvp = np.zeros((2 + 2 * pad_total, 2))
            Fjvm = np.zeros_like(Fjvp)
            for i in range(2):
                j = ep_idx[i]
                Fjvp[:, i] = TPJBSolver.getF(state + ep_jv * obj.bearing.fdZ(j + 1), obj)
                Fjvm[:, i] = TPJBSolver.getF(state - ep_jv * obj.bearing.fdZ(j + 1), obj)
            C = -(Fjvp[:2, :2] - Fjvm[:2, :2]) / (2 * ep_jv)

        out = {"iter": iter_count, "err": err}
        lambda_val = np.nan
        return state, matP, -JacF, C, lambda_val, out

    @staticmethod
    def getF(test_state: Array, obj: "TPJBSolver") -> Array:
        response = np.zeros(2 + 2 * obj.pad_count)
        pad_force = np.zeros((2, obj.pad_count))
        for pad_index in range(obj.pad_count):
            idx = TPJBSolver.pad_idx(pad_index + 1, obj.pad_count)
            pad_moment, pad_force_vec, *_ = TPJBSolver.solveP_simplified(
                test_state[idx - 1],
                obj.pressure_state.thetaTa[pad_index],
                obj.matTh_flat[:, pad_index],
                obj.matZ_flat[:, pad_index],
                obj.matP_flat[:, pad_index],
                obj.matC_flat[:, pad_index],
                obj.matT_flat[:, pad_index],
                obj.vecR[pad_index],
                obj.vecThAvg[pad_index],
                obj.matTh_fine[:, :, pad_index],
                obj.vecR_fine[pad_index],
                obj.vecThAvg_fine[pad_index],
                obj,
            )
            pad_force[:, pad_index] = pad_force_vec
            response[2 + pad_index] = pad_moment
        response[:2] = pad_force.sum(axis=1)
        return response

    @staticmethod
    def film_thickness_vec(
        Zpad: Array,
        Rb: float,
        Cb: float,
        Cp: float,
        Mp: float,
        thetaTa: float,
        matTh: Array,
    ) -> Array:
        ep = Zpad[:2]
        tl = Zpad[2]
        pv = Zpad[3]
        eca = np.arctan2(ep[1], ep[0])
        return (
            Cp
            - ep[0] * np.cos(matTh)
            - ep[1] * np.sin(matTh)
            - Cp * Mp * np.cos(matTh - thetaTa)
            - (Rb * np.sin(matTh - thetaTa)) * tl
            - pv * np.cos(matTh - eca)
        )

    @staticmethod
    def solveP_simplified(
        Z: Array,
        thetaTa: float,
        matTh: Array,
        nodeZ: Array,
        p: Array,
        c: Array,
        matT: Array,
        r: Array,
        th: Array,
        matTh_fine: Array,
        r_fine: Array,
        th_fine: Array,
        obj: "TPJBSolver",
    ):
        bearing = obj.bearing
        ref_state = obj.ref_state
        options = obj.options
        lubricant = obj.lubricant
        Nx = obj.nx
        Nz = obj.nz
        nNode = Nx * Nz
        Rb = bearing.Rb
        Lb = bearing.Lb
        Cb = bearing.Cb
        Cp = bearing.Cp
        Mp = bearing.Mp
        aPad = bearing.aPad
        shN = obj.ref_state.shN
        shB = obj.ref_state.shB
        NCP = obj.pressure_state.NCP
        pRef = ref_state.pRef
        pCav = ref_state.pCav
        pAmb = ref_state.pAmb
        iNP = obj.pressure_state.iNP
        P0 = (pAmb - pCav) / (pRef - pCav)
        f_fp = obj.asperity.f_fp
        f_fs = obj.asperity.f_fs
        f_ff_p = obj.asperity.f_ff_p
        f_ff_s = obj.asperity.f_ff_s
        f_ff = obj.asperity.f_ff
        f_ht = obj.asperity.f_ht
        sig = obj.asperity.sig
        f_p_cont = obj.asperity.f_p_cont

        jpx, jpy, padtilt, pvdisp, jvx, jvy, tvel, pvel = Z

        node_h = (
            Cp
            - jpx * np.cos(matTh)
            - jpy * np.sin(matTh)
            - Cp * Mp * np.cos(matTh - thetaTa)
            - padtilt * (Rb * np.sin(matTh - thetaTa))
            - pvdisp * np.cos(matTh - np.arctan2(jpy, jpx))
        )

        node_dhdt = (
            -jvx * np.cos(matTh)
            - jvy * np.sin(matTh)
            - tvel * (Rb * np.sin(matTh - thetaTa))
            - pvel * np.cos(matTh - np.arctan2(jpy, jpx))
        )

        nEle = (Nx - 1) * (Nz - 1)
        hh = node_h[NCP].mean(axis=1)
        dhh = node_dhdt[NCP].mean(axis=1)
        cX_ = Rb * matTh[NCP]
        cZ_ = nodeZ[NCP]

        H = hh / sig
        fp = f_fp(H)
        fs = f_fs(H)
        ff_p = f_ff_p(H)
        ff_s = f_ff_s(H)
        ht = f_ht(H / 3, sig)
        ff = f_ff(H / 3)

        CXZ = np.stack((cZ_, cX_), axis=2)
        CXZ = CXZ.transpose(1, 2, 0)

        B1 = shB[0:2, :]
        B2 = shB[2:4, :]
        B3 = shB[4:6, :]
        B4 = shB[6:8, :]

        def pagemul(Bk: Array) -> Array:
            return np.einsum('ab,bcn->acn', Bk, CXZ)

        Js1 = pagemul(B1)
        Js2 = pagemul(B2)
        Js3 = pagemul(B3)
        Js4 = pagemul(B4)

        def pagels(Js: Array, Bk: Array) -> Array:
            rhs = np.broadcast_to(Bk, (nEle, *Bk.shape)).copy()
            solved = np.linalg.solve(Js.transpose(2, 0, 1), rhs)
            return solved.transpose(1, 2, 0)

        Bs1 = pagels(Js1, B1)
        Bs2 = pagels(Js2, B2)
        Bs3 = pagels(Js3, B3)
        Bs4 = pagels(Js4, B4)

        detJ = Js1[0, 0, :] * Js1[1, 1, :] - Js1[0, 1, :] * Js1[1, 0, :]
        SumBtB = sum(
            np.einsum('eik, ejk -> eij', Bs.transpose(2, 0, 1), Bs.transpose(2, 0, 1))
            for Bs in (Bs1, Bs2, Bs3, Bs4)
        ).transpose(1, 2, 0)

        coefA = (hh ** 3) / (12 * lubricant.mu0) * detJ
        Ae_all = SumBtB * coefA

        Bs_sum = Bs1 + Bs2 + Bs3 + Bs4
        Wu = np.array([bearing.w, bearing.u])
        term1 = np.einsum('ijn,i->jn', Bs_sum, Wu).reshape(4, 1, nEle)
        Ns_sum = shN.sum(axis=0)
        term2 = np.broadcast_to(Ns_sum[:, None, None], (4, 1, nEle))

        Ce_all = (ht / 2 + sig * fs) * term1.transpose(2, 0, 1) - dhh * term2.transpose(2, 0, 1)
        Ce_all = (Ce_all.transpose(1, 2, 0) * detJ).transpose(0, 2, 1)
        Ce_all = Ce_all / (pRef - pCav)

        nNode = NCP.max() + 1
        A = np.zeros((nNode, nNode))
        np.add.at(
            A,
            (NCP[:, :, None], NCP[:, None, :]),
            Ae_all.transpose(2, 0, 1),
        )

        Cvec = np.zeros(nNode)
        np.add.at(Cvec, NCP, Ce_all[:, 0, :].T)

        p_tmp = p.copy()
        p_tmp[iNP] = 0.0
        Cvec -= A @ p_tmp
        A_comp = A[np.ix_(iNP, iNP)]
        F_ = np.linalg.solve(np.tril(A_comp), Cvec[iNP])
        KU = np.triu(A_comp)
        nNP = iNP.sum()
        P_ = np.zeros(nNP)
        P_[-1] = max(F_[-1] / KU[-1, -1], P0)
        for n in range(nNP - 2, -1, -1):
            rhs = -KU[n, n + 1 : nNP] @ P_[n + 1 : nNP] + F_[n]
            P_[n] = max(rhs / KU[n, n], P0)

        p_new = p.copy()
        p_new[iNP] = P_

        matP = p_new.reshape(Nz, Nx, order="F")
        matp = matP * (pRef - pCav) + pCav
        meanp = 0.25 * (
            matp[:-1, :-1]
            + matp[:-1, 1:]
            + matp[1:, :-1]
            + matp[1:, 1:]
        )
        M_lub = np.sum(meanp - pAmb, axis=(0, 1)) * r.mean() * Rb * aPad * np.pi / 180 / (Nx - 1) * Lb / (Nz - 1)
        h_fine = (
            Cp
            - jpx * np.cos(matTh_fine)
            - jpy * np.sin(matTh_fine)
            - Cp * Mp * np.cos(matTh_fine - thetaTa)
            - padtilt * (Rb * np.sin(matTh_fine - thetaTa))
            - pvdisp * np.cos(matTh_fine - np.arctan2(jpy, jpx))
        )
        p_cont_fine = f_p_cont(h_fine / sig)
        Nx_fine = matTh_fine.shape[1]
        mean_p_cont_fine = 0.25 * (
            p_cont_fine[:-1, :-1]
            + p_cont_fine[:-1, 1:]
            + p_cont_fine[1:, :-1]
            + p_cont_fine[1:, 1:]
        )
        F_lub = -np.sum(meanp - pAmb) * Rb * aPad * np.pi / 180 / (Nx - 1) * Lb / (Nz - 1)
        F_cont = -np.sum(mean_p_cont_fine) * Rb * aPad * np.pi / 180 / (Nx_fine - 1) * Lb / (Nz - 1)
        F = np.array([F_lub + F_cont, F_lub + F_cont])
        M_cont_fine = np.sum(mean_p_cont_fine) * Rb * aPad * np.pi / 180 / (Nx_fine - 1) * Lb / (Nz - 1)
        M = M_lub + M_cont_fine
        p_lub = matp
        p_cont = p_cont_fine
        return M, F, matP, p_lub, p_cont, np.array([F_lub, 0.0]), np.array([F_cont, 0.0])

    @staticmethod
    def sub_2d_mesh(nRow: int, nCol: int):
        matNN = np.arange(nRow * nCol).reshape(nRow, nCol, order="F")
        nEle = (nRow - 1) * (nCol - 1)
        c1 = (np.arange(nRow - 1)[:, None] + np.arange(0, nRow * (nCol - 1), nRow)).ravel(order="F")
        c2 = c1 + 1
        c3 = c2 + nRow - 1
        c4 = c1 + nRow - 1
        matNC = np.vstack((c1, c2, c3, c4)).T
        matEleType = np.zeros((nEle, 4), dtype=int)
        matNodalNC = matNC.copy()
        return matNC, matNodalNC, matEleType, matNN

    @staticmethod
    def sub_shape_funs(nEO: int):
        if nEO != 4:
            raise NotImplementedError("Only 4-node elements are implemented in the Python port.")
        nGI = 4
        weights = np.ones(nGI)
        points = np.array([
            [-1 / np.sqrt(3), 1 / np.sqrt(3), 1 / np.sqrt(3), -1 / np.sqrt(3)],
            [-1 / np.sqrt(3), -1 / np.sqrt(3), 1 / np.sqrt(3), 1 / np.sqrt(3)],
        ])
        shN = np.zeros((nGI, 4))
        shB = np.zeros((2 * nGI, 4))
        W11 = lambda xi: np.array([(1 - xi) / 2, (1 + xi) / 2, (1 + xi) / 2, (1 - xi) / 2])
        W12 = lambda xi: np.array([
            -0.75 * (1 - xi) * (1 + xi),
            +0.75 * (1 - xi) * (1 + xi),
            +0.75 * (1 - xi) * (1 + xi),
            -0.75 * (1 - xi) * (1 + xi),
        ])
        W21 = lambda eta: np.array([(1 - eta) / 2, (1 - eta) / 2, (1 + eta) / 2, (1 + eta) / 2])
        W22 = lambda eta: np.array([
            -0.75 * (1 - eta) * (1 + eta),
            -0.75 * (1 - eta) * (1 + eta),
            +0.75 * (1 - eta) * (1 + eta),
            +0.75 * (1 - eta) * (1 + eta),
        ])
        W11_all = np.zeros((nGI, 4))
        W12_all = np.zeros((nGI, 4))
        W21_all = np.zeros((nGI, 4))
        W22_all = np.zeros((nGI, 4))
        for i in range(nGI):
            xi = points[0, i]
            eta = points[1, i]
            shN[i, :] = (
                (eta / 2 - 1 / 2) * (xi / 2 - 1 / 2),
                -(eta / 2 - 1 / 2) * (xi / 2 + 1 / 2),
                (eta / 2 + 1 / 2) * (xi / 2 + 1 / 2),
                -(eta / 2 + 1 / 2) * (xi / 2 - 1 / 2),
            )
            shB[2 * i : 2 * i + 2, :] = np.array(
                [[eta - 1, 1 - eta, eta + 1, -eta - 1], [xi - 1, -xi - 1, xi + 1, 1 - xi]]
            ) / 4
            W11_all[i, :] = W11(xi)
            W12_all[i, :] = W12(xi)
            W21_all[i, :] = W21(eta)
            W22_all[i, :] = W22(eta)

        shW = lambda upA, upB: (W11_all + upA * W12_all) * (W21_all + upB * W22_all)
        shdW = lambda upA, upB: np.zeros_like(W11_all)
        shQ = np.zeros((4, 4))
        return shN, shB, shW, shdW, shQ, weights, points, nGI
